-- AlterTable
ALTER TABLE "KeywordStat" ADD COLUMN     "occurrences" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "read" SET DEFAULT 0,
ALTER COLUMN "ignored" SET DEFAULT 0,
ALTER COLUMN "replied" SET DEFAULT 0;
